/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * teste
 */
package univs.edu.telas.menuPrincipal;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import univs.edu.telas.login.GenericLogin;

/**
 *
 * @author GGrio
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public static boolean prevencao;
    public static boolean ajuda;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();

        carregarInfo();
    }

    public void carregarInfo() {
        if (prevencao == true) {

            lbTitulo.setText("Dicas de Prenvenção");

            lbTexto.setText("<html><ul><li>Não sobrecarregue as tomadas com diversos adaptadores acoplados a ela;<li>Em hipóteses alguma, armazene líquidos inflamáveis próximos a fontes de calor;<li>Antes de utilizar um equipamento, verifique se a sua voltagem é compatível com a da tomada;<li>Manter fósforos e isqueiros fora do alcance das crianças;<li>O Ibama alerta: provocar incêndios sem autorização é crime ambiental! A pena prevista é de reclusão, de dois a quatro anos, e multa (Lei nº 9.605/98 e Decreto nº 6.514/08).</ul>");
            lbTexto.setIcon(null);

            lbLink.setText("<html><u>Para mais informações clique aqui!");
            lbLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lbLink.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    try {
                        URI link = new URI("https://www.gov.br/ibama/pt-br");
                        Desktop.getDesktop().browse(link);
                    } catch (IOException | URISyntaxException erro) {
                        System.out.println(erro);
                    }
                }
            });

            lbVoltar.setText("Voltar");
            lbVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/iconSetaVoltar.png")));
            lbVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lbVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (prevencao == true) {
                        prevencao = false;
                        ajuda = false;
                    } else if (ajuda == true) {
                        prevencao = true;
                        ajuda = false;
                    }
                    new MenuPrincipal().setVisible(true);
                    dispose();
                }
            });

        } else if (ajuda == true) {
            lbTitulo.setText("  Sobre o Sistema");

            lbTexto.setText("<html><ul>O Incêndio S.O.S é um aplicativo de denúncia sobre incêndios para Desktop");
            lbTexto.setIcon(null);
            
            lbVoltar.setText("Voltar");
            lbVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/iconSetaVoltar.png")));
            lbVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lbVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (prevencao == true) {
                        prevencao = false;
                        ajuda = false;
                    } else if (ajuda == true) {
                        prevencao = true;
                        ajuda = false;
                    }
                    new MenuPrincipal().setVisible(true);
                    dispose();
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbAvancar = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbVoltar = new javax.swing.JLabel();
        lbTexto = new javax.swing.JLabel();
        lbLink = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu = new javax.swing.JMenu();
        mnSobre = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbAvancar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbAvancar.setForeground(new java.awt.Color(255, 255, 255));
        lbAvancar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAvancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/iconSetaAvancar.png"))); // NOI18N
        lbAvancar.setText("Avançar");
        lbAvancar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAvancar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lbAvancar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAvancarMouseClicked(evt);
            }
        });
        jPanel1.add(lbAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 100, 30));

        lbTitulo.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setText("  Seja Bem Vindo!");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 180, 30));

        lbVoltar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbVoltar.setForeground(new java.awt.Color(255, 255, 255));
        lbVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lbVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, 30));

        lbTexto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbTexto.setForeground(new java.awt.Color(255, 255, 255));
        lbTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 330, 220));

        lbLink.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbLink.setForeground(new java.awt.Color(255, 255, 255));
        lbLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbLinkMouseExited(evt);
            }
        });
        jPanel1.add(lbLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 180, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/backgroundMenu.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 370, 370));

        jMenu3.setBackground(new java.awt.Color(0, 0, 0, 0));
        jMenu3.setMargin(new java.awt.Insets(0, 170, 0, 0));
        jMenuBar1.add(jMenu3);

        jMenu.setText("Dicas de prevenção");
        jMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu);

        mnSobre.setText("Sobre");
        mnSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnSobre.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mnSobre.setMargin(new java.awt.Insets(5, 10, 5, 0));
        mnSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnSobre);

        jMenu4.setText("Login");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(0, 10, 0, 0));
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbAvancarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAvancarMouseClicked
        if (prevencao == false && ajuda == false) {
            prevencao = true;
            ajuda = false;
            new MenuPrincipal().setVisible(true);
            dispose();
        } else if (prevencao == true) {
            prevencao = false;
            ajuda = true;
            new MenuPrincipal().setVisible(true);
            dispose();
        } else if (ajuda == true) {
            new GenericLogin().setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_lbAvancarMouseClicked

    private void jMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMouseClicked
        prevencao = true;
        ajuda = false;
        new MenuPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuMouseClicked

    private void mnSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSobreMouseClicked
        ajuda = true;
        prevencao = false;
        new MenuPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnSobreMouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        new GenericLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void lbLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLinkMouseClicked

    }//GEN-LAST:event_lbLinkMouseClicked

    private void lbLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLinkMouseEntered
        lbLink.setForeground(Color.decode("#CCCCCC"));
    }//GEN-LAST:event_lbLinkMouseEntered

    private void lbLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLinkMouseExited
        lbLink.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbLinkMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAvancar;
    private javax.swing.JLabel lbLink;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbVoltar;
    private javax.swing.JMenu mnSobre;
    // End of variables declaration//GEN-END:variables
}
