/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package univs.edu.telas.usuario;

import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import univs.edu.dao.GenericDAO;
import univs.edu.denuncia.Denuncia;
import univs.edu.ibama.Ibama;
import univs.edu.usuario.Usuario;
import univs.edu.util.ManipularImagem;
import static univs.edu.util.ManipularImagem.getImgBytes;

/**
 *
 * @author GGrio
 */
public class Denunciar extends javax.swing.JFrame {

    Ibama ibama = new Ibama();
    GenericDAO dao = new GenericDAO();
    Denuncia denuncia = new Denuncia();
    BufferedImage imagem;
    DateTimeFormatter formatoData = DateTimeFormatter.ofPattern("dd/MM/yyyy-HH:mm:ss");
    LocalDateTime data = LocalDateTime.now();

    /**
     * Creates new form Denunciar
     */
    public Denunciar() {
        initComponents();
        addItem();
    }

    public void addItem() {
        jIbamas.removeAllItems();
        List<Ibama> ibamas = dao.listarObjetos("Ibama", "Undefined");
        for (Ibama ibama : ibamas) {
            jIbamas.addItem(ibama.getNomeIbama() + "-" + ibama.getCidadeIbama() + "/" + ibama.getEstadoIbama() + "-" + ibama.getEmailIbama());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNomeSuspeito = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfComplemento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfDescricaoSuspeito = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDetalhes = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSelecionar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jIbamas = new javax.swing.JComboBox<>();
        lbEvidencia = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Denuncie ao IBAMA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/cabecalho.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome do Suspeito:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        tfNomeSuspeito.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfNomeSuspeito.setToolTipText("Caso não Saiba o Nome do Suspeito, Pode-se Deixar o Campo em Branco");
        tfNomeSuspeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeSuspeitoActionPerformed(evt);
            }
        });
        jPanel1.add(tfNomeSuspeito, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, 35));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Endereço(rua):");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        tfEndereco.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfEndereco.setToolTipText("Nome da Rua");
        jPanel1.add(tfEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 200, 35));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Complemento:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        tfComplemento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfComplemento.setToolTipText("Exemplo: Centro");
        tfComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfComplementoActionPerformed(evt);
            }
        });
        jPanel1.add(tfComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 200, 35));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descrição do suspeito:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        tfDescricaoSuspeito.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(tfDescricaoSuspeito, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 200, 35));

        tfDetalhes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(tfDetalhes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 200, 90));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Detalhes do Incêndio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Evidência:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        btnSelecionar.setText("Selecionar Foto");
        btnSelecionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });
        btnSelecionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSelecionarKeyPressed(evt);
            }
        });
        jPanel1.add(btnSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 142, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("IBAMA:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        jIbamas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jIbamas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jIbamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIbamasActionPerformed(evt);
            }
        });
        jIbamas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jIbamasKeyPressed(evt);
            }
        });
        jPanel1.add(jIbamas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 153, 30));

        lbEvidencia.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(lbEvidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 400, 210));

        btnVoltar.setBackground(new java.awt.Color(255, 51, 153));
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        btnVoltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnVoltarKeyPressed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 80, 35));

        btnEnviar.setBackground(new java.awt.Color(255, 51, 153));
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        btnEnviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEnviarKeyPressed(evt);
            }
        });
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 80, 35));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/backgroundInfoDenunciaNotificacao.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, 438, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        JFileChooser fc = new JFileChooser();
        int res = fc.showOpenDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();

            try {
                imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 400, 300);

                lbEvidencia.setIcon(new ImageIcon(imagem));

            } catch (Exception ex) {
                // System.out.println(ex.printStackTrace().toString());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Você não selecionou nenhum arquivo!", "Aviso", 2);
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if (tfDescricaoSuspeito.getText().isEmpty() || tfDetalhes.getText().isEmpty() || tfEndereco.getText().isEmpty() || tfComplemento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos!", "Erro", 2);
        } else {
            String[] identificacao = jIbamas.getSelectedItem().toString().split("-");
            ibama = (Ibama) dao.pesquisarEmail(identificacao[2]);

            if (imagem != null) {
                denuncia.setEvidencias(getImgBytes(imagem));
            }

            denuncia.setDescricaoSuspeito(tfDescricaoSuspeito.getText());
            denuncia.setDetalhesIncendio(tfDetalhes.getText());
            denuncia.setIbama(ibama);
            denuncia.setUsuario(Usuario.usuario);
            denuncia.setEndereco(tfEndereco.getText());
            denuncia.setNomeSuspeito(tfNomeSuspeito.getText());
            denuncia.setDataEnvio(formatoData.format(data));
            denuncia.setCidade(Usuario.usuario.getCidadeUsuario());
            denuncia.setComplemento(tfComplemento.getText());
            denuncia.setTrote(false);

            dao.salvar(denuncia);
            new HomePageUsuario().setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnEnviarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEnviarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tfDescricaoSuspeito.getText().isEmpty() || tfDetalhes.getText().isEmpty() || tfEndereco.getText().isEmpty() || tfComplemento.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os Campos!", "Erro", 2);
            } else {
                String[] identificacao = jIbamas.getSelectedItem().toString().split("-");
                ibama = (Ibama) dao.pesquisarEmail(identificacao[2]);

                if (imagem != null) {
                    denuncia.setEvidencias(getImgBytes(imagem));
                }

                denuncia.setDescricaoSuspeito(tfDescricaoSuspeito.getText());
                denuncia.setDetalhesIncendio(tfDetalhes.getText());
                denuncia.setIbama(ibama);
                denuncia.setUsuario(Usuario.usuario);
                denuncia.setEndereco(tfEndereco.getText());
                denuncia.setNomeSuspeito(tfNomeSuspeito.getText());
                denuncia.setDataEnvio(formatoData.format(data));
                denuncia.setCidade(Usuario.usuario.getCidadeUsuario());
                denuncia.setComplemento(tfComplemento.getText());
                denuncia.setTrote(false);

                dao.salvar(denuncia);
                new HomePageUsuario().setVisible(true);
                dispose();
            }

        }
    }//GEN-LAST:event_btnEnviarKeyPressed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new HomePageUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVoltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnVoltarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            new HomePageUsuario().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnVoltarKeyPressed

    private void tfComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComplementoActionPerformed

    private void tfNomeSuspeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeSuspeitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeSuspeitoActionPerformed

    private void btnSelecionarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSelecionarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JFileChooser fc = new JFileChooser();
            int res = fc.showOpenDialog(null);

            if (res == JFileChooser.APPROVE_OPTION) {
                File arquivo = fc.getSelectedFile();

                try {
                    imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 400, 300);

                    lbEvidencia.setIcon(new ImageIcon(imagem));

                } catch (Exception ex) {
                    // System.out.println(ex.printStackTrace().toString());
                }

            } else {
                JOptionPane.showMessageDialog(null, "Você não selecionou nenhum arquivo!", "Aviso", 2);
            }
        }
    }//GEN-LAST:event_btnSelecionarKeyPressed

    private void jIbamasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIbamasKeyPressed

    }//GEN-LAST:event_jIbamasKeyPressed

    private void jIbamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIbamasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIbamasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Denunciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Denunciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Denunciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Denunciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Denunciar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jIbamas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEvidencia;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfDescricaoSuspeito;
    private javax.swing.JTextPane tfDetalhes;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNomeSuspeito;
    // End of variables declaration//GEN-END:variables
}
