/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package univs.edu.telas.usuario;

import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import univs.edu.bombeiro.CorpoDeBombeiros;
import univs.edu.dao.GenericDAO;
import univs.edu.telas.login.GenericLogin;
import univs.edu.usuario.Usuario;

/**
 *
 * @author GGrio
 */
public class HomePageUsuario extends javax.swing.JFrame {

    GenericDAO dao = new GenericDAO();
    Usuario usuario = new Usuario();
    CorpoDeBombeiros bombeiro = new CorpoDeBombeiros();
    DateTimeFormatter formatoData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    LocalDateTime data = LocalDateTime.now();

    public static boolean editar;

    /**
     * Creates new form HomePageUsuario
     */
    public HomePageUsuario() {
        initComponents();
        //jlTeste.setText("Bem Vindo " + Usuario.usuario.getNomeUsuario() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntNotificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDenunciar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlTeste = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        mnInfo = new javax.swing.JMenu();
        mnInfoIbama = new javax.swing.JMenuItem();
        mnBombeiro = new javax.swing.JMenuItem();
        configs = new javax.swing.JMenu();
        mnEditar = new javax.swing.JMenuItem();
        mnExcluir = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();
        mnsair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(450, 450));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bntNotificar.setBackground(new java.awt.Color(0, 0, 0, 0
        ));
        bntNotificar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bntNotificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/iconNotificarBombeiro.png"))); // NOI18N
        bntNotificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntNotificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNotificarActionPerformed(evt);
            }
        });
        bntNotificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bntNotificarKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Notificar");

        btnDenunciar.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnDenunciar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDenunciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/iconDenuncia.png"))); // NOI18N
        btnDenunciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDenunciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenunciarActionPerformed(evt);
            }
        });
        btnDenunciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDenunciarKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Denunciar");

        jlTeste.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/dicasDePrevencao.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntNotificar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDenunciar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jlTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(bntNotificar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(124, 124, 124)
                        .addComponent(btnDenunciar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(jlTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );

        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jMenu5.setMargin(new java.awt.Insets(0, 210, 0, 0));
        jMenuBar1.add(jMenu5);

        mnInfo.setText("Informações");
        mnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnInfo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mnInfo.setMargin(new java.awt.Insets(5, 10, 5, 10));
        mnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInfoActionPerformed(evt);
            }
        });

        mnInfoIbama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mnInfoIbama.setText("IBAMA");
        mnInfoIbama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInfoIbamaActionPerformed(evt);
            }
        });
        mnInfo.add(mnInfoIbama);

        mnBombeiro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mnBombeiro.setText("Corpo de Bombeiros");
        mnBombeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBombeiroActionPerformed(evt);
            }
        });
        mnInfo.add(mnBombeiro);

        jMenuBar1.add(mnInfo);

        configs.setText("Configurações");
        configs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        configs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        configs.setMargin(new java.awt.Insets(0, 0, 0, 10));

        mnEditar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mnEditar.setText("Editar");
        mnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEditarActionPerformed(evt);
            }
        });
        configs.add(mnEditar);

        mnExcluir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mnExcluir.setText("Excluir");
        mnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExcluirActionPerformed(evt);
            }
        });
        configs.add(mnExcluir);

        jMenuBar1.add(configs);

        mnSair.setText("Sair");
        mnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnSair.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });

        mnsair.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mnsair.setText("Sair");
        mnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnsairActionPerformed(evt);
            }
        });
        mnSair.add(mnsair);

        jMenuBar1.add(mnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntNotificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNotificarActionPerformed
        if (dao.pesquisarNotDen(Usuario.usuario, formatoData.format(data), "Notificação").size() == 3) {
            JOptionPane.showMessageDialog(null, "Limite de Notificações Diarias Atingido!", "Aviso", 2);
        } else {
            new Notificar().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_bntNotificarActionPerformed

    private void btnDenunciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenunciarActionPerformed
        if (dao.pesquisarNotDen(Usuario.usuario, formatoData.format(data), "Denuncia").size() == 3) {
            JOptionPane.showMessageDialog(null, "Limite de Denuncias Diarias Atingido!", "Aviso", 2);
        } else {
            new Denunciar().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnDenunciarActionPerformed

    private void mnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEditarActionPerformed
        editar = true;

        new CadastroUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnEditarActionPerformed

    private void mnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir sua conta?", "Excluir", 0, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dao.excluir(Usuario.usuario);
            new GenericLogin().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_mnExcluirActionPerformed

    private void mnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInfoActionPerformed

    }//GEN-LAST:event_mnInfoActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed

    }//GEN-LAST:event_mnSairActionPerformed

    private void mnBombeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBombeiroActionPerformed
        new Informacoes().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnBombeiroActionPerformed

    private void mnInfoIbamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInfoIbamaActionPerformed
        new Informacoes().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnInfoIbamaActionPerformed

    private void mnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnsairActionPerformed
        new GenericLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnsairActionPerformed

    private void bntNotificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bntNotificarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (dao.pesquisarNotDen(Usuario.usuario, formatoData.format(data), "Notificação").size() == 3) {
                JOptionPane.showMessageDialog(null, "Limite de Notificações Diarias Atingido!", "Aviso", 2);
            } else {
                new Notificar().setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_bntNotificarKeyPressed

    private void btnDenunciarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDenunciarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (dao.pesquisarNotDen(Usuario.usuario, formatoData.format(data), "Denuncia").size() == 3) {
                JOptionPane.showMessageDialog(null, "Limite de Denuncias Diarias Atingido!", "Aviso", 2);
            } else {
                new Denunciar().setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_btnDenunciarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntNotificar;
    private javax.swing.JButton btnDenunciar;
    private javax.swing.JMenu configs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlTeste;
    private javax.swing.JMenuItem mnBombeiro;
    private javax.swing.JMenuItem mnEditar;
    private javax.swing.JMenuItem mnExcluir;
    private javax.swing.JMenu mnInfo;
    private javax.swing.JMenuItem mnInfoIbama;
    private javax.swing.JMenu mnSair;
    private javax.swing.JMenuItem mnsair;
    // End of variables declaration//GEN-END:variables
}
