/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package univs.edu.telas.usuario;

import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import univs.edu.bombeiro.CorpoDeBombeiros;
import univs.edu.dao.GenericDAO;
import univs.edu.notificacao.Notificacao;
import univs.edu.usuario.Usuario;

/**
 *
 * @author GGrio
 */
public class Notificar extends javax.swing.JFrame {

    CorpoDeBombeiros bombeiro = new CorpoDeBombeiros();
    Notificacao not = new Notificacao();
    GenericDAO dao = new GenericDAO();
    DateTimeFormatter formatoData = DateTimeFormatter.ofPattern("dd/MM/yyyy-HH:mm:ss");
    LocalDateTime data = LocalDateTime.now();

    /**
     * Creates new form Notificar
     */
    public Notificar() {
        initComponents();
        addItem();
    }

    public void addItem() {
        jTipos.removeAllItems();
        jTipos.addItem("Florestal");
        jTipos.addItem("Residencial");
        jTipos.addItem("Automoveis");
        jTipos.addItem("Usinas");
        jCorposDeBombeiros.removeAllItems();
        List<CorpoDeBombeiros> bombeiros = dao.listarObjetos("Bombeiro", "Undefined");
        for (CorpoDeBombeiros bombeiro : bombeiros) {
            jCorposDeBombeiros.addItem(bombeiro.getCompanhiaBatalhao() + "-" + bombeiro.getCidadeBombeiro() + "/" + bombeiro.getEstadoBombeiro());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfRua = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfComplemento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfDuracao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfAbrangencia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCorposDeBombeiros = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTipos = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDescricao = new javax.swing.JTextPane();
        btnVoltar = new javax.swing.JButton();
        btnEvnviar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Notifique ao Corpo de Bombeiros");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/cabecalho.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 438, 89));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfRua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfRua.setToolTipText("Nome da Rua");
        jPanel3.add(tfRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 35));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Endereço(rua):");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        tfComplemento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfComplemento.setToolTipText("Exemplo: Centro");
        jPanel3.add(tfComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 200, 35));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Complemento:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        tfDuracao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(tfDuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 35));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Duração:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Abrangência:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        tfAbrangencia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(tfAbrangencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 200, 35));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Corpo de Bombeiros:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jCorposDeBombeiros.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCorposDeBombeiros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCorposDeBombeiros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCorposDeBombeiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCorposDeBombeirosActionPerformed(evt);
            }
        });
        jPanel3.add(jCorposDeBombeiros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 200, 35));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo de Incendio:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        jTipos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jTipos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 200, 35));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descriçao:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        tfDescricao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(tfDescricao);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, 80));

        btnVoltar.setBackground(new java.awt.Color(255, 51, 153));
        btnVoltar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        btnVoltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnVoltarKeyPressed(evt);
            }
        });
        jPanel3.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 80, 35));

        btnEvnviar.setBackground(new java.awt.Color(255, 51, 153));
        btnEvnviar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEvnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEvnviar.setText("Enviar");
        btnEvnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEvnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvnviarActionPerformed(evt);
            }
        });
        btnEvnviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEvnviarKeyPressed(evt);
            }
        });
        jPanel3.add(btnEvnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 80, 35));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/backgroundInfoDenunciaNotificacao.jpg"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 437, 360));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEvnviarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEvnviarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tfRua.getText().isEmpty() || tfComplemento.getText().isEmpty() || tfDuracao.getText().isEmpty() || tfAbrangencia.getText().isEmpty() || tfDescricao.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!", "Erro", 2);
            } else {
                String[] identificacao = jCorposDeBombeiros.getSelectedItem().toString().split("-");
                bombeiro = (CorpoDeBombeiros) dao.pesquisarIdentificacao(identificacao[0]);

                not.setCidadeOcorrencia(Usuario.usuario.getCidadeUsuario());
                not.setRuaOcorrencia(tfRua.getText());
                not.setAbrangencia(tfAbrangencia.getText());
                not.setDescricao(tfDescricao.getText());
                not.setCorpoDeBombeiros(bombeiro);
                not.setUsuario(Usuario.usuario);
                not.setTipo(jTipos.getSelectedItem().toString());
                not.setDuracao(tfDuracao.getText());
                not.setDataEnvio(formatoData.format(data));
                not.setComplementoOcorrencia(tfComplemento.getText());
                not.setTrote(false);

                dao.salvar(not);
                new HomePageUsuario().setVisible(true);
                dispose();
            }

        }
    }//GEN-LAST:event_btnEvnviarKeyPressed

    private void btnEvnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvnviarActionPerformed
        if (tfRua.getText().isEmpty() || tfComplemento.getText().isEmpty() || tfDuracao.getText().isEmpty() || tfAbrangencia.getText().isEmpty() || tfDescricao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!", "Erro", 2);
        } else {
            String[] identificacao = jCorposDeBombeiros.getSelectedItem().toString().split("-");
            bombeiro = (CorpoDeBombeiros) dao.pesquisarIdentificacao(identificacao[0]);

            not.setCidadeOcorrencia(Usuario.usuario.getCidadeUsuario());
            not.setRuaOcorrencia(tfRua.getText());
            not.setAbrangencia(tfAbrangencia.getText());
            not.setDescricao(tfDescricao.getText());
            not.setCorpoDeBombeiros(bombeiro);
            not.setUsuario(Usuario.usuario);
            not.setTipo(jTipos.getSelectedItem().toString());
            not.setDuracao(tfDuracao.getText());
            not.setDataEnvio(formatoData.format(data));
            not.setComplementoOcorrencia(tfComplemento.getText());
            not.setTrote(false);

            dao.salvar(not);
            new HomePageUsuario().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnEvnviarActionPerformed

    private void btnVoltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnVoltarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            new HomePageUsuario().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnVoltarKeyPressed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new HomePageUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jCorposDeBombeirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCorposDeBombeirosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCorposDeBombeirosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvnviar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jCorposDeBombeiros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jTipos;
    private javax.swing.JTextField tfAbrangencia;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextPane tfDescricao;
    private javax.swing.JTextField tfDuracao;
    private javax.swing.JTextField tfRua;
    // End of variables declaration//GEN-END:variables
}
